Supermarket/Supmakt/Supmakt/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^admin/', admin.site.urls),

	# 全文搜索框架
	url(r'^search/', include('haystack.urls')),

	# 上传部件自动调用的上传地址
	url(r'^ckeditor/', include("ckeditor_uploader.urls")),
	url(r'^login.html/', include("login.urls", namespace='login')),
	url(r'^goods/', include("goods.urls", namespace='goods')),
	url(r'^index/', include("index.urls", namespace='index')),
	url(r'^shopcart/', include("shopcart.urls", namespace='shopcart')),
]

Supermarket/Supmakt/login/urls.py
from django.conf.urls import url
from django.views.static import serve
from login.views import *

urlpatterns = [
	url(r'^$', LoginView.as_view(), name='login_in_view'),
	url(r'^reg.html/$', RegistorView.as_view(), name='registor_view'),
	url(r'^infor.html/$', InforView.as_view(), name='infor_view'),
	url(r'^center/$', CenterView.as_view(), name='center_View'),
	url(r'^SendCode/$', SendCodeView.as_view(), name='SendCodeView'),
	url(r'^quit/$', QuitView.as_view(), name='QuitView'),
]

Supermarket/Supmakt/login/models.py
from datetime import datetime

from django.core import validators
from django.db import models
from basemodle.basemodel import BaseModel


class UserTable(BaseModel):
	# 性别选项
	sex_choices = (
		(1, '男'),
		(2, "女"),
		(3, "保密"),
	)
	nickname = models.CharField(verbose_name='昵称',
	                            max_length=20,
	                            null=True,
	                            blank=True,
	                            )
	phone = models.CharField(verbose_name='手机号码',
	                         validators=[validators.RegexValidator(r'^1[3-9]\d{9}$', '手机号码格式错误')],
	                         max_length=12)
	password = models.CharField(verbose_name='密码',
	                            max_length=64,
	                            )
	gender = models.SmallIntegerField(verbose_name='性别',
	                                  default=3,
	                                  choices=sex_choices,
	                                  )
	head = models.ImageField(verbose_name='用户头像',
	                         upload_to='img',
	                         default='default/infortx.png',
	                         )
	birthday = models.DateField(verbose_name='出生日期',
	                            null=True,
	                            blank=True,
	                            )
	school_name = models.CharField(verbose_name='学校名称',
	                               max_length=50,
	                               null=True,
	                               blank=True,
	                               )
	address = models.CharField(verbose_name='学校详细地址',
	                           max_length=100,
	                           null=True,
	                           blank=True,
	                           )
	hometown = models.CharField(verbose_name='老家',
	                            max_length=100,
	                            null=True, blank=True,
	                            )

	class Meta:
		db_table = 'users'
		verbose_name = '用户管理'
		verbose_name_plural = verbose_name

	def __str__(self):
		return self.phone

Supermarket/Supmakt/login/forms.py
from django import forms
from django.core import validators
from django.core.exceptions import ValidationError
from django import forms

from login.helper import hash_password
from login.models import UserTable


class UserModelForm(forms.ModelForm):
	repassword = forms.CharField(max_length=16,
	                             min_length=6,
	                             error_messages={'required': '请填写确认密码', },
	                             widget=forms.PasswordInput(attrs={'class': 'login-password',
	                                                               'placeholder': '请确认密码'}
	                                                        )
	                             )

	verify = forms.CharField(required=True,
	                         widget=forms.TextInput(attrs={'class': 'reg-yzm',
	                                                       'placeholder': '输入验证码'}
	                                                ),
	                         error_messages={'required': '验证码为空'}
	                         )

	class Meta:
		model = UserTable
		fields = ['phone', 'password']
		error_messages = {
			'phone': {'required': '号码不能为空'},
			'password': {'required': '密码不能为空',
			             'max_length': '密码不能大于16个字符',
			             'min_length': '密码不能少于6个字符'},
		}
		widgets = {
			'phone': forms.TextInput(attrs={'class': 'login-name',
			                                'placeholder': '请输入手机号'}
			                         ),
			'password': forms.PasswordInput(attrs={'class': 'login-password',
			                                       'placeholder': '请输入密码'}
			                                ),
		}

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['password'].validators.append(validators.MaxLengthValidator(16))
		self.fields['password'].validators.append(validators.MinLengthValidator(6))

	def clean_phone(self):
		phone = self.cleaned_data.get('phone')
		user = UserTable.objects.filter(phone=phone).first()
		if user:
			raise forms.ValidationError('该账号已被注册')
		else:
			return phone

	def clean_verify(self):
		verify_code = self.data.get('verify')
		session_code = self.data.get('session_code')
		if session_code is None:
			raise forms.ValidationError('请先获取验证码')
		if verify_code != session_code:
			raise forms.ValidationError('验证码错误')
		return

	def clean(self):
		cleaned_data = super().clean()
		pw1 = cleaned_data.get('password')
		pw2 = cleaned_data.get('repassword')
		if pw1 and pw2 and pw1 != pw2:
			raise forms.ValidationError({'repassword': '两次密码不一致'})
		else:
			if pw1:
				"""对密码进行加密处理"""
				cleaned_data['password'] = hash_password(pw1)
			return cleaned_data


class LoginForm(forms.ModelForm):
	class Meta:
		model = UserTable
		fields = ['phone', 'password']

		error_messages = {
			'phone': {'required': '电话输入为空'},
			'password': {'required': '密码输入为空'}
		}
		widgets = {
			'phone': forms.TextInput(attrs={'class': 'login-name',
			                                'placeholder': '请输入手机号'
			                                }
			                         ),
			'password': forms.PasswordInput(attrs={'class': 'login-password',
			                                       'placeholder': '请输入密码'
			                                       }
			                                )
		}

	# def clean_phone(self):
	# 	phone = self.cleaned_data.get('phone')
	# 	user = UserTable.objects.filter(phone=phone).first()
	# 	if user is None:
	# 		raise forms.ValidationError("号码不存在,请注册")
	# 	else:
	# 		return phone

	def clean(self):
		cleaned_data = self.cleaned_data
		phone = cleaned_data.get('phone')
		user = UserTable.objects.filter(phone=phone).first()
		if user is None:
			raise forms.ValidationError({"phone": "号码不存在,请注册"})
		else:
			"""用户存在则判断密码是否正确"""
			password = cleaned_data.get('password', '')
			pwd_db = user.password
			password = hash_password(password)
			if pwd_db != password:
				raise forms.ValidationError({'password': '密码不正确'})
			else:
				cleaned_data['user'] = user
				return cleaned_data


class InforForm(forms.ModelForm):
	sex_choices = (
		(1, '男'),
		(2, "女"),
		(3, "保密"),
	)

	class Meta:
		model = UserTable
		fields = ['nickname', 'birthday', 'head', 'gender',
		          'school_name', 'address', 'hometown', 'phone']
		widgets = {
			'nickname': forms.TextInput(attrs={'class': 'infor-tele', 'placeholder': '默契'}),
			'birthday': forms.TextInput(attrs={'class': 'infor-tele', 'placeholder': '1991-10-15'}),
			'school_name': forms.TextInput(attrs={'class': 'infor-tele', 'placeholder': '就读于哪个学校'}),
			'address': forms.TextInput(attrs={'class': 'infor-tele', 'placeholder': '详细地址'}),
			'hometown': forms.TextInput(attrs={'class': 'infor-tele', 'placeholder': '来自哪里'}),
			'phone': forms.TextInput(attrs={'class': 'infor-tele', 'placeholder': '13012345678'}),

			# 'gender': {'class': 'infor-tele', 'placeholder': 'adfa'},
			# 'head': {'class': 'daf', 'placeholder': 'adfa'},
			# 'birthday': {'class': 'infor-tele', 'placeholder': '1991-11-05'},
			# 'school_name': {'class': 'infor-tele', 'placeholder': '就读于哪个学校'},
			# 'address': {'class': 'infor-tele', 'placeholder': '详细地址'},
			# 'hometown': {'class': 'infor-tele', 'placeholder': '来自哪里'},
			# 'phone': {'class': 'infor-tele', 'placeholder': '13012345678'},
		}

# def clean(self):
# 	cleaned_data = super().clean()
# 	return cleaned_data

Supermarket/Supmakt/login/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, reverse

# Create your views here.
from django.views import View

from login.forms import *
from login.models import *


class LoginView(View):
	"""登录账户"""

	def get(self, request):
		id = request.session.get('ID')
		if not id:
			# 若账号不存在
			form = LoginForm()
			context = {
				'form': form
			}
			return render(request, 'login/login.html', context)
		user = UserTable.objects.filter(pk=id).first()
		context = {
			"user": user
		}
		return render(request, 'goods/member.html', context)

	def post(self, request):
		form = LoginForm(request.POST)
		if form.is_valid():
			"""验证成功"""
			# 注册session
			user = form.cleaned_data.get('user')
			request.session['ID'] = user.pk
			request.session['phone'] = user.phone
			request.session.set_expiry(0)

			return redirect(reverse('login:login_in_view'))
		else:
			context = {
				'form': form
			}
			return render(request, 'login/login.html', context)


# user = UserTable.objects.filter(phone=phone)


class RegistorView(View):
	"""注册账户"""

	def get(self, request):
		form = UserModelForm()
		context = {
			'form': form
		}
		return render(request, 'login/reg.html', context)

	def post(self, request):
		# 1.接收数据
		# 2.验证数据
		data = request.POST.dict()
		session_code = request.session.get('session_code')
		data['session_code'] = session_code

		form = UserModelForm(data)
		if form.is_valid():
			"""验证通过"""
			form.save()
			return redirect(reverse("login:login_in_view"))
		else:
			"""验证失败"""
			context = {
				'form': form
			}
		return render(request, 'login/reg.html', context)


class InforView(View):
	def get(self, request):
		id = request.session.get('ID')
		user = UserTable.objects.filter(pk=id).first()
		show_info = user.head
		form = InforForm(instance=user)
		context = {
			'form': form,
			'user': user
		}
		return render(request, 'login/infor.html', context)

	def post(self, request):
		id = request.session.get('ID')
		user = UserTable.objects.filter(pk=id).first()
		"""修改数据"""
		form = InforForm(request.POST, request.FILES, instance=user)
		form.save()
		# user.head = request.FILES['head']
		# user.nickname = request.POST.get('nickname')
		# user.gender = request.POST.get('gender')
		# user.birthday = request.POST.get('birthday')
		# user.school_name = request.POST.get('school_name')
		# user.address = request.POST.get('address')
		# user.hometown = request.POST.get('hometown')
		# user.phone = request.POST.get('phone')
		# form = InforForm(request.POST)
		# user.save()
		return redirect(reverse('login:center_View'))


# else:
# 	return render(request, 'login/infor.html')


class CenterView(View):
	def get(self, request):
		id = request.session.get('ID')
		if not id:
			user = UserTable.objects.filter(pk=id).first()
			context = {
				'user': user
			}
			return render(request, 'goods/member.html', context)
		return redirect(reverse('login:login_in_view'))


class SendCodeView(View):
	"""生成验证码"""

	def post(self, request):
		mobile = request.POST.get('mobile')  # 获取html表单提交过来的电话号码
		res = UserTable.objects.filter(phone=mobile).exists()
		if res:
			"""若填写的电话号码已存在 则提示用户已存在"""
			data = {'status': '403', 'message': '该用户已注册,请直接登录'}
		else:
			"""进行验证"""
			import random
			codelist = [str(random.randint(0, 9)) for _ in range(0, 4)]
			num_code = ''.join(codelist)  # 模拟生成随机验证码
			request.session['session_code'] = num_code  # 保存系统生成的验证码
			request.session.set_expiry(60)
			print('**********{}***************'.format(num_code))
			data = {'status': '200',
			        'session_code': num_code}
		return JsonResponse(data)


class QuitView(View):
	def get(self, request):
		request.session.clear()
		return redirect(reverse('index:index_view'))

	def post(self, request):
		pass

Supermarket/Supmakt/templates/login/login.html
{% extends 'extend_temp/extend_temp.html' %}
{% load static %}

<!DOCTYPE html>
<html>
{#	<head>#}
{#		<meta charset="utf-8">#}
{#		<meta http-equiv="X-UA-Compatible" content="IE=edge">#}
{#		<title>超市</title>#}
{#        <meta name="description" content="">#}
{#        <meta name="keywords" content="">#}
{#        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">#}
{#        <meta name="renderer" content="webkit">#}
{#        <meta http-equiv="Cache-Control" content="no-siteapp" />#}
{#        <link rel="icon" type="image/png" href="/theme/default/images/favicon.png">#}
{#		<link href="{% static 'css/amazeui.min.css' %}" rel="stylesheet" type="text/css" />#}
{#		<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />#}
{#		<script src="{% static 'js/jquery-1.10.2.min.js' %}"></script>#}
{#		<script src="{% static 'js/time.js' %}"></script>#}
{#	</head>#}
{% block parent %}
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">登录</a>
            </h1>
	    </header>
	    <div style="height: 49px;"></div>
	    <!--<div class="login-logo">
	    	<img src="images/logo.png" />
	    </div>-->
	    <div style="height: 3rem;"></div>
        <form action="" method="post" novalidate>
            {% csrf_token %}
           {{ form.phone }}
            <p style="color: red">
                {{ form.errors.phone.0 }}
            </p>
            {{ form.password }}
             <p style="color: red;">
                {{ form.errors.password.0 }}
            </p>
           <p style="font-size: 18px;color: red;width: 100%;text-align: center">{{ reload }}</p>
            <input type="submit" class="login-btn" value="我要登录">
        </form>

	    <div class="agree">
	    	<a href="{% url 'login:registor_view' %}">免费注册</a>
	    	<a href="forgetpassword.html" class="forget">忘记密码？</a>
	    </div>
	    <div class="line"></div>
	    <div class="line-text">第三方账号登录</div>
	    <ul class="second-login">
	    	<li><a href=""><img src="{% static 'images/wxlogin.png' %}"/></a></li>
	    	<li><a href=""><img src="{% static 'images/qqlogin.png' %}"/></a></li>
	    	<li><a href=""><img src="{% static 'images/sinalog.png' %}"/></a></li>
	    </ul>
{% endblock %}

</html>

Supermarket/Supmakt/templates/login/reg.html
{% extends 'extend_temp/extend_temp.html' %}
{% load static %}
{% block parent %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">注册</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
    <!--<div class="login-logo">
        <img src="images/logo.png" />
    </div>-->
    <div style="height: 3rem;"></div>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.phone }}
        {{ form.errors.phone.0 }}
        {{ form.password }}
        {{ form.errors.password.0 }}
        {{ form.repassword }}
        {{ form.errors.repassword.0 }}
        <div class="yzm" style="margin-top: 1.5rem;">
            {{ form.verify }}
            <input type="button" class="yzm-hq" value="获取验证码"/>
        </div>
        {{ form.errors.verify.0 }}
        <input type="submit" class="login-btn" value="立即注册">
    </form>


    <div class="agree">
        <input type="checkbox" name="checkbox" value="同意" checked="">&nbsp;同意
        <a href="" class="xy">《用户协议》</a>
        <div class="r-login">已有账号，请<a href="{% url 'login:login_in_view' %}" class="l-login">登录</a></div>
    </div>
{% endblock %}
{% block footer %}
    <script>
        $('.yzm-hq').on('click', function () {
            {#1. 获取手机号码#}
            var phone = $('#id_phone').val();
            if (phone.length != 11) {
                alert('手机号码位数不正确')
                return false
            }
            {#console.log(phone)#}
            {#获取输入的输入验证码#}
            var input_verify_code = $('#id_verify').val()
            data = {
                "mobile": phone,
                "input_verify_code": input_verify_code,
                "csrfmiddlewaretoken": "{{ csrf_token }}"
            }
            that = this;
            $.post("{% url 'login:SendCodeView' %}", data, function (data) {
                {#data 为回调响应数据#}
                {#console.log(data.status)#}
                if (data.status == 200) {
                    //1.修改按钮颜色
                    $(that).attr('disabled', 'disabled');
                    $(that).css('background-color', 'grey');
                    var time = 60;
                    var msg = time + '秒后重新发送';
                    $(that).val(msg);
                    var timer = window.setInterval(function () {
                        --time;
                        if (time == 0) {
                            window.clearInterval(timer);
                            $(that).removeAttr('disabled');
                            $(that).css('background-color', '#76bb2a');
                            msg = 60 + '秒后重新发送';
                            $(that).val(msg)
                            return;
                        }
                        msg = time + '秒后重新发送';
                        $(that).val(msg)
                    }, 1000)

                }
                else {
                    alert(data.message)
                }
            })

        })
    </script>
{% endblock %}

</html>